DJANGORESIZED_DEFAULT_SIZE = [50, 100]
DJANGORESIZED_DEFAULT_QUALITY = 95
DJANGORESIZED_DEFAULT_KEEP_META = True
DJANGORESIZED_DEFAULT_FORCE_FORMAT = 'PNG'
DJANGORESIZED_DEFAULT_FORMAT_EXTENSIONS = {'PNG': '.png'}
DJANGORESIZED_DEFAULT_NORMALIZE_ROTATION = False
